import { type NextPage } from "next";

import Head from "next/head";
import { ReposShowcase } from "@modules/ReposShowcase";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-stone-200">
        <div className=" text-slate-800">
          {/* Details Part */}
          <div className="flex flex-col text-left leading-3">
            <ReposShowcase />
            <p className="mb-3 text-5xl font-bold">Orwa Shams</p>
            <p className="text-2xl">Fullstack dev</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
